# Netlify Configuration for Teasers CLE - Next.js

[build]
  command = "npm run build"
  publish = "out"

# Node version
[build.environment]
  NODE_VERSION = "20"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
  from = "/campaign"
  to = "https://gofund.me/bd89734c"
  status = 301
  force = true

# Form success redirect (optional)
# Uncomment to redirect to custom success page
# [[redirects]]
#   from = "/"
#   to = "/?success=true"
#   status = 200
#   force = false
#   conditions = {Role = ["form-submitted"]}
